using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.Models;

/* Generated by chatgpt 4o to tie the table data */
public class EventWithPrice
{
    public string Id { get; set; } = null!;
    public string? Image { get; set; }
    public string? Title { get; set; }
    public DateTime EventDate { get; set; }
    public string? Location { get; set; }
    public string? Description { get; set; }

    public List<PackageDto> Packages { get; set; } = new();
}

public class PackageDto
{
    public string Title { get; set; } = null!;
    public string? SeatingArrangement { get; set; }
    public string? Placement { get; set; }
    public decimal? Price { get; set; }
    public string? Currency { get; set; } = "$";
}
/* Generated by chatgpt 4o to tie the table data */

